all:
	gcc a4client1.c -o a4client1
	gcc a4server1.c -l sqlite3 -o a4server1
	gcc a4client2.c -o a4client2
	gcc a4client3.c -o a4client3
	
	rm a4ServerLog.txt
	rm a4Client1Log.txt
	rm a4Client2Log.txt
	rm a4Client3Log.txt
